#!/bin/sh

DOCKER="${DOCKER:-podman}"
IMAGE="${IMAGE:-ghcr.io/ricardobranco777/susepkg:latest}"

if [ "$1" = "--version" ] ; then
	latest=$(curl -s https://api.github.com/repos/ricardobranco777/susepkg/tags | jq -Mr '.[0].name')
	if [ "$latest" != $("$DOCKER" run --rm "$IMAGE" --version) ] ; then
		echo "Latest version available: $latest" >&2
	fi
fi

exec "$DOCKER" run --rm -e DEBUG "$IMAGE" "$@"
